import Head from "next/head";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>NFT Market</title>
        <meta name="description" content="NFT Market"></meta>
        <link rel="icon" href="./favicon.ico"></link>
      </Head>
      <body>{children}</body>
    </html>
  )
}
