import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from './provider';
import Header from "@/components/header";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import "./app.css";
import "./index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
    </body>
    </html>
  );
}
