[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
	{ access = "read", path = "./images/" },
	{ access = "read", path = "./broadcast" },
]

remappings = [
	'@openzeppelin=lib/openzeppelin-contracts/',
	'@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
solc_version = "0.8.20"


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
