import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './style/globals.css'
import '@rainbow-me/rainbowkit/styles.css'
import { RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { QueryClientProvider } from '@tanstack/react-query'
import { WagmiProvider } from 'wagmi'
import { wagmiConfig, client } from './components/provider/Web3Provider'
import ThirdwebClient from './components/provider/ThirdwebClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NFTMarket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebClient>
          <WagmiProvider config={wagmiConfig}>
            <QueryClientProvider client={client}>
              <RainbowKitProvider>{children}</RainbowKitProvider>
            </QueryClientProvider>
          </WagmiProvider>
        </ThirdwebClient>
      </body>
    </html>
  )
}
